# Generated by Django 5.2.1 on 2025-05-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare')], max_length=50)),
                ('add_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
